apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: LoadBalancer
  ports:
    - name: frontend-service-port
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: frontend-service